### ISSUE TITLE
provide dictionary?

### ISSUE THREAD

**Issue by atomicoo** [IepIweidieng/common-tl#1]
Thanks for you great work first. Then, as mentioned, could you provide you dictionary?

**Comment by IepIweidieng** [comment]
The dictionary data were from the online dictionaries compiled by the Ministry of Education of Taiwan. It is recommended to use the officially released dictionary data.

Among them, the following dictionaries are recommended for use:
- *臺灣閩南語常用詞辭典* (*Dictionary of Frequently-Used Taiwan Minnan*). Ministry of Education.
    - The official data release site is not available for now, but the data can be retrieved from https://github.com/g0v/moedict-data-twblg/blob/master/uni/詞目總檔.csv
        - Format: CSV (comma-separated values)
- *國語辭典簡編本* (*Concised Mandarin Chinese Dictionary*). Ministry of Education.
    - Filename: `dict_concised_2014_20220627` https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/dict_concised_download.html
        - Format: XLSX (Excel Spreadsheet XML)
- *臺灣客家語常用詞辭典* (*Dictionary of Frequently-Used Taiwan Hakka*) Ministry of Education.
    - Please refer to the post *提供《臺灣客家語常用詞辭典》文字內容資料下載* (*The text data of «Dictionary of Frequently-Used Taiwan Hakka» has been made available for download*) https://hakkadict.moe.edu.tw/cgi-bin/gs32/gsweb.cgi/login?o=dwebmge&gourl=/cgi-bin/gs32/gsweb.cgi/newsearch?&menuid=gsnews
        - Format: ODS (OpenDocument Spreadsheet)

The downloaded files need to be converted (or exported via "Save as") into TSV (tab-separated values) format, because TSV is currently the only format which the dictionary reader ([`ctl_dict.py`](https://github.com/IepIweidieng/common-tl/blob/master/ctl_dict.py)) accepts.

The field definition also needs to be specified when the dictionary reader is invoked. See the definition of function [`main()`](https://github.com/IepIweidieng/common-tl/blob/9b3b522e24235157c0bb19b2c94cfa8615bbded7/ch2rm.py#L174-L188) in [`ch2rm.py`](https://github.com/IepIweidieng/common-tl/blob/master/ch2rm.py) for reference.

**TODO**:
- [x] document this in [`README.md`](https://github.com/IepIweidieng/common-tl/blob/master/README.md)

**Comment by IepIweidieng** [comment]
The preliminary instructions on preparing the dictionary text files using the aforementioned dictionary data released by the Ministry of Education of Taiwan have been added to `README.md` in b3020577d115847d3188965a64d3fdad2c745256, see <https://github.com/IepIweidieng/common-tl#dictionary-preparation>.

There are no plans to release the requested dictionary text files because these files may have modifications which have prevented them from being redistributable due to the CC BY-ND 3.0 TW license applied on the source data by the Ministry of Education of Taiwan.
